FROM nginx:stable-alpine as prod-stage

COPY --from=mdm2 /mdm2/app/dist /usr/share/nginx/html
COPY docker/development/default.conf /etc/nginx/conf.d/default.conf

ENTRYPOINT ["nginx", "-g", "daemon off;"]
EXPOSE 4444